[2020-06-15 16:35:39,873] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[maximum recursion depth exceeded]
[2020-06-15 16:35:39,874] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,874] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,874] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,875] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,875] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,875] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,875] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,875] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,875] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,875] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,875] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,875] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,875] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,875] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,875] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,875] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,876] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,876] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,876] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,876] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,876] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,876] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,876] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,877] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,877] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,877] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,877] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,877] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,877] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,877] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,877] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,877] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,877] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,877] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,878] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,878] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,878] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,878] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,878] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,878] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,878] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,878] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,878] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,878] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,878] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,878] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,878] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,879] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,879] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,879] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,879] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,879] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,879] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,879] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,879] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,879] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,879] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,879] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,879] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,879] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,880] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,880] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,880] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,880] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,880] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,880] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,880] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,880] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,880] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,880] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,880] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,881] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,881] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,881] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,881] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,881] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,881] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,881] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,881] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,881] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,881] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,881] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,881] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,882] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,883] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,883] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,883] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,883] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,883] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,883] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,883] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,883] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,883] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,883] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,883] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,883] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,884] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,884] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,884] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,884] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,884] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,884] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,884] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,884] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,884] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,884] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,884] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,884] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,885] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,885] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,885] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,885] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,885] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,885] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,885] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,885] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,885] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,885] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,885] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,885] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,886] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,886] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,886] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,886] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,886] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,886] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,886] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,886] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,886] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,886] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,886] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,886] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,887] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,887] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,887] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,887] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,887] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,887] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,887] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,887] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,887] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,887] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,887] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,887] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,888] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,888] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,888] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,888] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,888] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,888] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,888] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,888] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,888] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,888] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,888] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,889] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,889] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,889] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,889] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,889] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,889] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,889] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,889] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,889] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,889] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,889] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,889] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,889] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,890] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,890] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,890] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,890] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,890] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,890] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,890] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,890] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,890] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,890] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,890] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,890] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,890] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,891] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,891] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,891] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,891] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,891] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,891] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,891] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,891] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,891] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,891] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,891] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,892] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,892] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,892] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,892] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,892] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,892] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,892] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,892] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,892] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,892] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,892] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,893] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,893] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,893] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,893] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,893] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,893] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,893] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,893] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,893] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,893] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,893] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,893] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,893] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,894] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,894] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,894] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,894] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,894] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,894] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,894] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,894] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,894] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,894] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,894] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,895] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,895] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,895] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,895] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,895] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,895] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,895] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,895] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,895] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,895] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,895] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,895] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,896] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,896] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,896] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,896] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,896] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,896] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,896] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,896] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,896] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,896] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,896] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,896] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,896] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,897] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,897] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,897] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,897] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,897] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,897] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,897] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,897] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,897] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,897] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,897] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,897] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,898] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,898] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,898] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,898] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,898] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,898] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,898] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,898] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,898] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,898] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,899] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,899] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,899] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,899] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,899] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,899] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,899] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,899] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,899] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,899] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,899] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,899] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,900] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,900] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,900] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,900] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,900] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,900] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,900] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,900] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,900] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,900] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,900] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,901] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,901] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,901] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,901] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,901] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,901] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,901] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,901] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:39,901] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,918] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[maximum recursion depth exceeded]
[2020-06-15 16:35:57,919] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,919] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,919] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,919] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,919] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,919] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,919] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,919] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,920] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,920] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,920] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,920] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,920] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,920] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,920] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,920] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,920] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,920] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,920] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,920] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,920] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,921] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,921] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,924] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,924] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,924] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,924] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,924] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,924] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,924] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,924] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,924] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,924] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,924] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,924] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,925] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,925] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,925] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,925] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,925] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,925] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,925] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,925] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,925] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,925] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,925] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,926] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,926] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,926] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,926] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,926] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,926] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,926] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,927] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,927] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,927] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,927] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,927] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,927] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,927] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,927] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,927] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,927] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,927] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,927] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,928] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,928] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,928] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,928] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,928] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,928] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,928] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,928] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,928] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,928] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,928] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,928] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,928] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,929] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,929] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,929] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,929] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,929] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,929] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,929] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,929] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,929] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,929] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,929] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,930] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,930] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,930] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,930] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,930] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,930] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,930] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,930] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,930] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,930] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,930] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,931] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,932] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,932] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,932] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,932] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,932] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,932] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,932] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,932] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,932] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,932] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,932] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,932] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,933] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,933] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,933] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,933] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,933] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,933] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,933] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,933] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,933] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,933] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,933] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,934] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,934] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,934] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,934] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,934] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,934] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,934] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,934] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,934] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,934] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,934] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,934] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,934] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,935] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,935] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,935] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,935] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,935] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,935] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,935] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,935] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,935] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,935] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,935] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,935] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,936] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,936] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,936] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,936] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,936] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,936] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,936] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,936] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,936] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,936] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,936] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,936] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,936] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,937] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,937] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,937] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,937] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,937] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,937] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,937] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,937] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,937] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,937] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,937] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,937] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,938] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,938] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,938] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,938] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,938] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,938] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,938] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,938] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,938] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,938] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,938] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,938] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,939] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,939] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,939] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,939] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,939] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,939] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,939] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,939] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,939] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,939] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,939] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,940] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,940] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,940] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,940] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,940] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,940] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,940] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,940] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,940] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,940] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,940] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,940] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,940] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,941] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,941] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,941] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,941] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,941] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,941] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,941] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,941] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,941] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,941] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,941] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,942] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,942] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,942] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,942] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,942] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,942] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,942] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,942] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,942] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,943] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,944] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,944] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,944] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,944] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,944] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,944] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,944] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,944] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,944] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,944] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,944] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,944] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,944] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,945] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,945] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,945] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,945] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,945] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,945] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,945] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,945] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,945] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,945] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,945] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,946] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,946] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,946] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,946] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,946] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,946] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,946] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,946] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,946] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,946] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,946] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,947] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,947] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,947] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,947] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,947] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,947] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,947] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,947] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,947] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,947] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,947] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,947] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,947] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,948] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,948] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,948] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,948] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,948] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,948] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,948] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,948] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,948] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,948] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,949] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,949] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:35:57,949] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:[local variable 'response_obj' referenced before assignment]
[2020-06-15 16:36:49,867] common_api.py->get_access_token line:39 [INFO] : 调用获取access_token接口成功
[2020-06-15 16:36:49,869] common_api.py->get_default_access_token line:48 [INFO] : 获取access_token成功，access_token为：[34_sO5i5My__ZTyZa0wu7-yQd7TBF8lCcEBHxW2cYbPqqwyWbqdKW-R6VC02fpFnOcen_RcewwJRZmfAJL9tdtU_QEET1MXB8KFAUZ0DZGKMUFcgZrbYpXhlqYqgQMnwxVWnqYVN6A2Bs4e-6NaALQfAJAGRW]
[2020-06-15 16:36:50,417] common_api.py->add_tags line:63 [INFO] : 新增用户标签成功，新增的标签为：[z4a8g]
[2020-06-15 16:36:50,418] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:['tag']
[2020-06-15 16:38:09,564] common_api.py->get_access_token line:39 [INFO] : 调用获取access_token接口成功
[2020-06-15 16:38:09,566] common_api.py->get_default_access_token line:48 [INFO] : 获取access_token成功，access_token为：[34_QjpNm9QTdmZPUNZDVNmQhgUxmYyuceaqKr3VuM8-XuuNBiM-Tbp3Iy3K1pkrPbjCaiOSnAu-IGROR4phe5euPNo5_9yYJlagM77BmcQDHkDwA2iDLHF89N2-XesFkio-4KK4Mj-e4Yki3nQaJVSdAIAWIF]
[2020-06-15 16:38:10,115] common_api.py->add_tags line:63 [INFO] : 新增用户标签成功，新增的标签为：[b48Dr]
[2020-06-15 16:38:10,115] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:['tag']
[2020-06-15 16:41:31,628] common_api.py->get_access_token line:39 [INFO] : 调用获取access_token接口成功
[2020-06-15 16:41:31,630] common_api.py->get_default_access_token line:48 [INFO] : 获取access_token成功，access_token为：[34_Gm9V64RNcfg_ZdUclUgi_M5IWGZTBbtntedj9kIpjaEhKgfSL5nLrEuL2sdF0lHtrQdoSZYYwBrFvzBU_xk5vUn_p2_MW_Vi-ArGgKwpv5JzO8vWavxq3xL2HeAIrk8BMK-b121ZaxZMcyPOWEKeACALTZ]
[2020-06-15 16:41:32,157] common_api.py->add_tags line:63 [INFO] : 新增用户标签成功，新增的标签为：[EqKc6]
[2020-06-15 16:41:32,157] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:['tag']
[2020-06-15 16:42:05,924] common_api.py->get_access_token line:39 [INFO] : 调用获取access_token接口成功
[2020-06-15 16:42:05,927] common_api.py->get_default_access_token line:48 [INFO] : 获取access_token成功，access_token为：[34_myBHt6c7Re5qCZlEupj7gGkF2hf5ieoapGXxf3UyGeb7x5ow3rG_ZsZoyNBD47VfbjwuN2WBI_lnxuueLvkF-xAtmcdg2oe29t16nUjmXZgRiATi7UoWTlGO_q8f7inaJh3yZiklLzBPhof6GJDeADAQTN]
[2020-06-15 16:42:06,483] common_api.py->add_tags line:63 [INFO] : 新增用户标签成功，新增的标签为：[rVbLg]
[2020-06-15 16:42:06,484] common_api.py->add_tags line:66 [ERROR] : 新增用户标签失败，失败的原因是:['tag']
[2020-06-15 16:50:35,255] common_api.py->get_access_token line:39 [INFO] : 调用获取access_token接口成功
[2020-06-15 16:50:35,256] common_api.py->get_default_access_token line:48 [INFO] : 获取access_token成功，access_token为：[34_qdHwAkQXqXHFa9HG0f88V8qvSkepw1ZELMhKlxxBH-V6EgAAQrJ4I4BJgXK1elxni7FyOZ81-CsWmM0uOtfUvZs0mYc6qdI_LPp2kEdooI_TkX_oE_riGvBLvXE71xn2xOkpjVXeE4AKQPuTLDRdADATLZ]
[2020-06-15 16:50:35,679] common_api.py->get_access_token line:39 [INFO] : 调用获取access_token接口成功
[2020-06-15 16:50:35,680] common_api.py->get_default_access_token line:48 [INFO] : 获取access_token成功，access_token为：[34_qdHwAkQXqXHFa9HG0f88V8qvSkepw1ZELMhKlxxBH-V6EgAAQrJ4I4BJgXK1elxni7FyOZ81-CsWmM0uOtfUvZs0mYc6qdI_LPp2kEdooI_TkX_oE_riGvBLvXE71xn2xOkpjVXeE4AKQPuTDZJdADAVRB]
[2020-06-15 16:50:36,213] common_api.py->look_for_makedtags line:77 [INFO] : 获取公众号已创建的标签成功
[2020-06-15 16:50:36,767] common_api.py->edit_tags line:93 [INFO] : 编辑标签成功
[2020-06-15 16:51:48,451] common_api.py->get_access_token line:39 [INFO] : 调用获取access_token接口成功
[2020-06-15 16:51:48,452] common_api.py->get_default_access_token line:48 [INFO] : 获取access_token成功，access_token为：[34_ArYQ79lv_S_FizXjx7_MZPfborALulPgDP7wCtbOFu8clXy8jNTOYOmauV9mpAdZoKBvYQEiC0zYtaQgpKXKULglSDNLnUKJE6PcBu5LOs-C0o72EggdoJy515UpOkmAognlVVFtWuA1mb6xNSOjAGAAFB]
[2020-06-15 16:51:49,223] common_api.py->get_access_token line:39 [INFO] : 调用获取access_token接口成功
[2020-06-15 16:51:49,224] common_api.py->get_default_access_token line:48 [INFO] : 获取access_token成功，access_token为：[34_ArYQ79lv_S_FizXjx7_MZPfborALulPgDP7wCtbOFu8clXy8jNTOYOmauV9mpAdZoKBvYQEiC0zYtaQgpKXKULglSDNLnUKJE6PcBu5LOs-C0o72EggdoJy515UpOkmAognlVVFtWuA1mb6xMBWjAGAXMH]
[2020-06-15 16:51:49,767] common_api.py->look_for_makedtags line:77 [INFO] : 获取公众号已创建的标签成功
[2020-06-15 16:51:50,351] common_api.py->edit_tags line:93 [INFO] : 编辑标签成功
